[package]

name = "DankFishing"
version = "0.0.1"
authors = ["VoxWave <victor_bankowski@hotmail.com>"]

[[bin]]

name = "DankFishing"

[dependencies.sdl2]
git = "https://github.com/AngryLawyer/rust-sdl2"
